FROM ubuntu:20.04

# x86-64
# aarch64
ARG IONCUDE_ARCHITECTURE=aarch64

# No tty
ENV DEBIAN_FRONTEND=noninteractive

# Apache 2.4 + PHP-7.4-FPM
RUN apt-get update \
    # Tools
    && apt-get -y --no-install-recommends install \
        curl \
        ca-certificates \
        nano \
        zip \
        unzip \
        git \
    # Supervisor
    && apt-get -y --no-install-recommends install \
        supervisor \
    # MySQL Client
    && apt-get -y --no-install-recommends install \
        mariadb-client-10.3 \
    # Install Apache + PHP
    && apt-get -y --no-install-recommends install \
        apache2 \
        php-fpm php7.4-mysql php7.4-xml php7.4-gd php7.4-mbstring php7.4-bcmath php7.4-zip php-memcache php-redis \
        php7.4-curl \
        php-xdebug \
    # Configure Apache + PHP
    && a2enconf php7.4-fpm \
    && a2enmod proxy \
    && a2enmod proxy_fcgi \
    && a2enmod rewrite \
    # Clean
    && rm -rf /var/lib/apt/lists/*

# Drupal Tools
#RUN curl -sf -o /usr/bin/composer -L https://getcomposer.org/download/1.5.5/composer.phar \
#    && chmod +x /usr/bin/composer \
#    && curl -sf -o /usr/bin/drush -L https://github.com/drush-ops/drush/releases/download/8.1.15/drush.phar \
#    && chmod +x /usr/bin/drush \
#    && curl https://drupalconsole.com/installer -L -o /usr/bin/drupal \
#    && chmod +x /usr/bin/drupal \
    # Composer & Drush & Drupal Console need write access to www-data home
    # TODO refactor and replace with access user
#    && chown www-data:www-data /var/www


#RUN docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp
#RUN docker-php-ext-install -j$(nproc) gd

#RUN pecl install redis && docker-php-ext-enable redis


RUN cd /tmp \
    && ls /usr/lib/php \
    && curl -o ioncube.tar.gz https://downloads.ioncube.com/loader_downloads/ioncube_loaders_lin_${IONCUDE_ARCHITECTURE}.tar.gz \
    && tar -xvvzf ioncube.tar.gz \
    && mv ioncube/ioncube_loader_lin_7.4.so /usr/lib/php/20190902/ \
    && rm -Rf ioncube.tar.gz ioncube \
    && echo "zend_extension=/usr/lib/php/20190902/ioncube_loader_lin_7.4.so" > /etc/php/7.4/fpm/conf.d/00_docker-php-ext-ioncube_loader_lin_7.4.ini
    
    
# Supervisor
RUN mkdir -p /run/php/
COPY config/supervisord/supervisord.conf /etc/supervisor/supervisord.conf
COPY config/supervisord/conf.d/ /etc/supervisor/conf.d/

# Apache Configuration
COPY ./config/apache/000-default.conf /etc/apache2/sites-available/000-default.conf

# PHP Configuration
COPY config/php/fpm/php.ini /etc/php/7.4/fpm/php.ini
COPY config/php/fpm/pool.d/www.conf /etc/php/7.4/fpm/pool.d/www.conf
COPY config/php/fpm/xdebug.ini /etc/php/7.4/mods-available/xdebug.ini

#phpinfo
RUN mkdir /var/www/html/docroot
COPY ./scripts/index.php /var/www/html/docroot/

# Startup script to change uid/gid (if environment variable passed) and start supervisord in foreground
COPY ./scripts/start.sh /start.sh
RUN chmod 755 /start.sh

EXPOSE 80

CMD ["/bin/bash", "/start.sh"]